### ISSUE TITLE
Provide an API for the developer to query the un-packager

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-common#22]
Suggested by @mpeuster: `GET /api/v1/packages/<process_id>`

**Comment by mpeuster** [comment]
see also: sonata-nfv/tng-sdk-package#33

**Comment by jbonnet** [comment]
Include `package_process_status` field which can contain `success` or `failed`

**Comment by jbonnet** [comment]
Endpoint agreed with @mpeuster: `…/packages/status/:process_uuid` (sonata-nfv/tng-sdk-package#49)
