### ISSUE TITLE
Create OpenAPI documentation for this component

### ISSUE THREAD

**Issue by jbonnet** [sonata-nfv/tng-gtk-common#35]

**Comment by felipevicens** [comment]
Hey @jbonnet, it is a good opportunity to define the OpenAPIs' folder to automate later the centralized documentation via Jenkins. Which folder we can use for openapi? /docs/openapi. /openapi?

**Comment by jbonnet** [comment]
Currently being written on a swagger. json, in a /doc folder..Em 30/04/2018 18:32, Felipe Vicens <notifications@github.com> escreveu:Hey @jbonnet, it is a good opportunity to define the OpenAPIs' folder to automate later the centralized documentation via Jenkins. Which folder we can use for openapi? /docs/openapi. /openapi?

**Comment by jbonnet** [comment]
Closed via #36, with a pending issue: how to represent both a `requestBody` parameter and a `header` one...
